# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a70ab762f4618fb17b8ac55b8ba5f38a302cb0cc563ada50c93a24fcf3cd79216548ef412f12498ac944054d16e402d11cad7dae30e039f38ddb84d78a23b6a

test:
  secret_key_base: 3c656228c148701dd1c9a020f86a4f8865b2bc2ec29a52962810b191de5da76fee55e96c82cd3105e6ad024f337bc9e9e28af74c671989d7a8c676b086a641a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
